return {
  version = "0.1.0",
  channel = "main",
  files = {
    { path = "/startup.lua", source = "startup.lua", mode = "replace" },
    { path = "/aeon/boot/init.lua", source = "aeon/boot/init.lua", mode = "replace" },
    { path = "/aeon/boot/bootstrap.lua", source = "aeon/boot/bootstrap.lua", mode = "replace" },
    { path = "/aeon/core/config.lua", source = "aeon/core/config.lua", mode = "replace" },
    { path = "/aeon/core/logger.lua", source = "aeon/core/logger.lua", mode = "replace" },
    { path = "/aeon/core/registry.lua", source = "aeon/core/registry.lua", mode = "replace" },
    { path = "/aeon/core/service.lua", source = "aeon/core/service.lua", mode = "replace" },
    { path = "/aeon/shell/shell.lua", source = "aeon/shell/shell.lua", mode = "replace" },
    { path = "/aeon/services/svc_registry.lua", source = "aeon/services/svc_registry.lua", mode = "replace" },
    { path = "/aeon/services/svc_auth.lua", source = "aeon/services/svc_auth.lua", mode = "replace" },
    { path = "/aeon/services/svc_net.lua", source = "aeon/services/svc_net.lua", mode = "replace" },
    { path = "/aeon/drivers/display.lua", source = "aeon/drivers/display.lua", mode = "replace" },
    { path = "/aeon/drivers/modem.lua", source = "aeon/drivers/modem.lua", mode = "replace" },
    { path = "/aeon/bin/help.lua", source = "aeon/bin/help.lua", mode = "replace" },
    { path = "/aeon/bin/clear.lua", source = "aeon/bin/clear.lua", mode = "replace" },
    { path = "/aeon/bin/ls.lua", source = "aeon/bin/ls.lua", mode = "replace" },
    { path = "/aeon/bin/cat.lua", source = "aeon/bin/cat.lua", mode = "replace" },
    { path = "/aeon/bin/devices.lua", source = "aeon/bin/devices.lua", mode = "replace" },
    { path = "/aeon/bin/role.lua", source = "aeon/bin/role.lua", mode = "replace" },
    { path = "/aeon/bin/hostname.lua", source = "aeon/bin/hostname.lua", mode = "replace" },
    { path = "/aeon/bin/reboot.lua", source = "aeon/bin/reboot.lua", mode = "replace" },
    { path = "/aeon/bin/svc.lua", source = "aeon/bin/svc.lua", mode = "replace" },
    { path = "/aeon/bin/login.lua", source = "aeon/bin/login.lua", mode = "replace" },
    { path = "/aeon/bin/whoami.lua", source = "aeon/bin/whoami.lua", mode = "replace" },
    { path = "/aeon/bin/update.lua", source = "aeon/bin/update.lua", mode = "replace" },
    { path = "/aeon/etc/aeon.cfg", source = "aeon/etc/aeon.cfg", mode = "keep" },
    { path = "/aeon/etc/role.cfg", source = "aeon/etc/role.cfg", mode = "keep" },
    { path = "/aeon/etc/users.cfg", source = "aeon/etc/users.cfg", mode = "keep" },
    { path = "/aeon/etc/network.cfg", source = "aeon/etc/network.cfg", mode = "keep" },
    { path = "/aeon/etc/update.cfg", source = "aeon/etc/update.cfg", mode = "keep" },
  }
}
