return {
  version = "0.7.0",
  profile = "server",
  channel = "main",
  files = {
    { path = "/startup.lua", source = "startup.lua", mode = "replace" },
    { path = "/aeon/boot/init.lua", source = "aeon/boot/init.lua", mode = "replace" },
    { path = "/aeon/boot/bootstrap.lua", source = "aeon/boot/bootstrap.lua", mode = "replace" },
    { path = "/aeon/core/config.lua", source = "aeon/core/config.lua", mode = "replace" },
    { path = "/aeon/core/events.lua", source = "aeon/core/events.lua", mode = "replace" },
    { path = "/aeon/core/service_contract.lua", source = "aeon/core/service_contract.lua", mode = "replace" },
    { path = "/aeon/core/permissions.lua", source = "aeon/core/permissions.lua", mode = "replace" },
    { path = "/aeon/core/app.lua", source = "aeon/core/app.lua", mode = "replace" },
    { path = "/aeon/core/kernel.lua", source = "aeon/core/kernel.lua", mode = "replace" },
    { path = "/aeon/core/logger.lua", source = "aeon/core/logger.lua", mode = "replace" },
    { path = "/aeon/core/registry.lua", source = "aeon/core/registry.lua", mode = "replace" },
    { path = "/aeon/core/service.lua", source = "aeon/core/service.lua", mode = "replace" },
    { path = "/aeon/apps/server.lua", source = "aeon/apps/server.lua", mode = "replace" },
    { path = "/aeon/services/svc_log.lua", source = "aeon/services/svc_log.lua", mode = "replace" },
    { path = "/aeon/services/svc_registry.lua", source = "aeon/services/svc_registry.lua", mode = "replace" },
    { path = "/aeon/services/svc_auth.lua", source = "aeon/services/svc_auth.lua", mode = "replace" },
    { path = "/aeon/services/svc_tasks.lua", source = "aeon/services/svc_tasks.lua", mode = "replace" },
    { path = "/aeon/services/svc_net.lua", source = "aeon/services/svc_net.lua", mode = "replace" },
    { path = "/aeon/services/svc_server.lua", source = "aeon/services/svc_server.lua", mode = "replace" },
    { path = "/aeon/drivers/display.lua", source = "aeon/drivers/display.lua", mode = "replace" },
    { path = "/aeon/drivers/modem.lua", source = "aeon/drivers/modem.lua", mode = "replace" },
    { path = "/aeon/bin/update.lua", source = "aeon/bin/update.lua", mode = "replace" },
    { path = "/aeon/etc/aeon.cfg", source = "aeon/etc/aeon.cfg", mode = "keep" },
    { path = "/aeon/etc/users.cfg", source = "aeon/etc/users.cfg", mode = "keep" },
    { path = "/aeon/etc/network.cfg", source = "aeon/etc/network.cfg", mode = "keep" },
  }
}
